# Anhang A – Vorbereitung

Prüfen, ob PyTorch installiert ist und die Apple-GPU (MPS) nutzen kann.

In [1]:
import torch

print(torch.__version__)

2.14.0


In [2]:
print(torch.backends.mps.is_available())

True


In [3]:
# Tensoren mit 0 bis 4 Dimensionen
tensor_0d = torch.tensor(1)
tensor_1d = torch.tensor([1, 2, 3])
tensor_2d = torch.tensor([[1, 2], [3, 4]])
tensor_3d = torch.zeros(2, 3, 4)
tensor_4d = torch.zeros(2, 3, 4, 5)

for dimension, tensor in enumerate(
    [tensor_0d, tensor_1d, tensor_2d, tensor_3d, tensor_4d]
):
    print(f"{dimension}D: Shape = {tensor.shape}")
    print(tensor)
    print()

0D: Shape = torch.Size([])
tensor(1)

1D: Shape = torch.Size([3])
tensor([1, 2, 3])

2D: Shape = torch.Size([2, 2])
tensor([[1, 2],
        [3, 4]])

3D: Shape = torch.Size([2, 3, 4])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

4D: Shape = torch.Size([2, 3, 4, 5])
tensor([[[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]]],


        [[[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.]],

         [[0., 0., 0., 0., 0.],
          [0., 0., 0., 0., 0.],
          [0., 0., 0., 0.,

### Achtung: „3D“ bei Tensoren ≠ „3D“ in der Mathematik

Bei Tensoren zählt **D** die **Achsen** (`tensor.ndim`), also wie viele Indizes man braucht, um einen einzelnen Wert anzusprechen. Wie viele Werte auf einer Achse liegen, spielt dafür keine Rolle.

| Begriff | Bedeutung | `shape` | `ndim` |
|---|---|---|---|
| 3D-Vektor | 3 Komponenten, z. B. ein Punkt im Raum (x, y, z) | `[3]` | **1** |
| 3D-Matrix (3×3) | 3 Zeilen × 3 Spalten, z. B. eine Rotation im Raum | `[3, 3]` | **2** |
| 3D-Tensor | Werte entlang 3 Achsen, z. B. `torch.zeros(2, 3, 4)` | `[2, 3, 4]` | **3** |

In der Mathematik meint „3D“ also den **Raum mit 3 Richtungen**, bei Tensoren die **Anzahl der Achsen**.

Faustregel: `ndim` = Länge von `shape` = Anzahl der öffnenden eckigen Klammern am Anfang der Ausgabe. Die Zahlen *in* `shape` geben an, wie lang jede Achse ist.

In [7]:
vektor_3d = torch.tensor([1.0, 2.0, 3.0])  # 3D-Vektor aus der Mathematik
matrix_3x3 = torch.eye(3)                  # 3×3-Matrix („3D-Matrix“)
tensor_3d = torch.zeros(2, 3, 4)           # 3D-Tensor

for name, t in [("3D-Vektor", vektor_3d), ("3×3-Matrix", matrix_3x3), ("3D-Tensor", tensor_3d)]:
    print(f"{name:<11} shape = {list(t.shape)},  ndim = {t.ndim}")
    print(t)

3D-Vektor   shape = [3],  ndim = 1
tensor([1., 2., 3.])
3×3-Matrix  shape = [3, 3],  ndim = 2
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
3D-Tensor   shape = [2, 3, 4],  ndim = 3
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [12]:
import torch.nn.functional as F

y = torch.tensor([1.0])
x1 = torch.tensor([1.1])
w1 = torch.tensor([2.2])
b = torch.tensor([-0.5])
z = x1 * w1 + b
a = torch.sigmoid(z)
loss = F.binary_cross_entropy(a, y)

print('z: ', z, ' a: ', a, ' loss: ', loss)


z:  tensor([1.9200])  a:  tensor([0.8721])  loss:  tensor(0.1368)
